service: skill2rural-backend

useDotenv: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

frameworkVersion: '>=1.72.0'

provider:
  name: aws
  runtime: nodejs18.x

functions:
  nestApp:
    handler: dist/serverless.handler
    events:
      - http:
          path: /
          method: ANY
      - http:
          path: /{proxy+}
          method: ANY

package:
  exclude:
    - node_modules/**
    - .gitignore
    - .git/**
